// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArVlPlj_hLciM-7mfm_87adGljo70Bqlc',
    appId: '1:89542398713:web:e3aeae84055aaebedb4828',
    messagingSenderId: '89542398713',
    projectId: 'seniordesign-28d60',
    authDomain: 'seniordesign-28d60.firebaseapp.com',
    storageBucket: 'seniordesign-28d60.appspot.com',
    measurementId: 'G-18F053K8HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf2aXKOEGwYLyKX4BZfZxYbyD80bvRVT4',
    appId: '1:89542398713:android:98522444871a191fdb4828',
    messagingSenderId: '89542398713',
    projectId: 'seniordesign-28d60',
    storageBucket: 'seniordesign-28d60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjBgbTtIqfhOLRuKTHuwRPKsNdfHATSLI',
    appId: '1:89542398713:ios:b74af6b5d61a2e17db4828',
    messagingSenderId: '89542398713',
    projectId: 'seniordesign-28d60',
    storageBucket: 'seniordesign-28d60.appspot.com',
    iosBundleId: 'com.example.seniorDesign',
  );
}
